# Generated by Django 5.0.6 on 2024-05-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocial',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
